# Generated by Django 4.1.7 on 2023-03-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=250)),
                ('plan', models.CharField(max_length=50)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('termsInMonth', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenantId', models.CharField(db_index=True, max_length=250, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone', models.CharField(max_length=250, null=True)),
                ('companyName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('logoTxtImg', models.ImageField(blank=True, null=True, upload_to='')),
                ('logoTxt', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
