# Generated by Django 4.1.7 on 2023-03-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_api', '0002_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
