# Generated by Django 4.1.7 on 2023-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_api', '0003_alter_branch_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='slugName',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
