# Generated by Django 4.1.7 on 2023-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_api', '0006_surveyeditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyeditor',
            name='options',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
