# Generated by Django 4.1.7 on 2023-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_api', '0007_alter_surveyeditor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyeditor',
            name='labelName',
            field=models.CharField(max_length=250),
        ),
    ]
